dist: trusty

services:
  - docker

install: true




#services:
#  - docker
#
#install: true
#
#env:
#  - VERSION_FILE=build.properties
#
stages:
  - name: increment_version
      if: branch = release
  - name: release_to_docker
      if: branch = release

jobs:
  include:
    - stage: increment_version
      script:
        - if [ "$TRAVIS_BRANCH" == "release" ]; then

          fi

    - stage: release_to_docker
       script:
         - if [ "$TRAVIS_BRANCH" == "release" ]; then

           fi