services:
  - docker

install: true

env:
  - VERSION_FILE=build.properties

stages:
  - name: increment_version
    if: branch = release
  - name: release_to_docker
    if: branch = release

jobs:
  include:
    - stage: increment_version
      script:
        - if [ "$TRAVIS_BRANCH" == "release" ]; then
            perl -i -pe '$a=1 if(!$a && s/\b(\d+)(?=\D*$)/$1+1/e);' $VERSION_FILE;
            git add $VERSION_FILE;
            git commit -m 'Increment version [ci skip]';
            git push https://$RUNNER_LOGIN:$RUNNER_PASSWORD@github.com/vostoksystems/kafka.git HEAD:release;
          fi

    - stage: release_to_docker
      script:
        - if [ "$TRAVIS_BRANCH" == "release" ]; then
            export PROJECT_VERSION=$(cat $FILE_WITH_VERSION | grep -oP "(?<=version\s=\s).+" | sed -n "1p");

            docker login -u=$DOCKER_REGISTRY_USERNAME -p=DOCKER_REGISTRY_PASSWORD;
            docker build . -t vostoksystems/kafka:$PROJECT_VERSION -t vostoksystems/kafka:latest;
            docker push vostoksystems/kafka:$PROJECT_VERSION;
            docker push vostoksystems/kafka:latest;
          fi