dist: trusty

services:
  - docker

install: true




#services:
#  - docker
#
#install: true
#
#env:
#  - VERSION_FILE=build.properties
#
stages:
  - name: increment_version
      if: branch = release

jobs:
  include:
    - stage: increment_version
      script:
          - ./gradlew testIntegration

