version: '3.1'

services:
  zoo:
      image: zookeeper
      hostname: zoo
      ports:
        - 2181:2181

  kafka:
      image: vostoksystems/kafka
      ports:
        - 9092:9092
      environment:
        ZK_CONNECT: zoo:2181
